# Pre-requisite: ./deploy.sh from root directory

# (Recommended) Container configuration example
storage:
  type: postgres
  connection_string: "postgresql://openexcept:openexcept@postgres:5432/openexcept"

# Local file system storage configuration example
# storage:
#   local_path: ~/.openexcept

# (Recommended) config using OpenAI embeddings
# embedding:
#   class: OpenAIEmbedding
#   # kwargs:
#   #   api_key: your_openai_api_key_here or configure the OPENAI_API_KEY environment variable
#   similarity_threshold: 0.9

embedding:
  class: SentenceTransformerEmbedding
  kwargs:
    model_name: all-mpnet-base-v2
  similarity_threshold: 0.8